---
- name: check if sources already exist
  stat:
    path: "/opt/{{ sources_prometheu | basename }}"
  register: sources_result
  
- name: download component sources
  become: true
  become_user: root
  get_url:
    url: "{{ sources_prometheus }}"
    dest: "/opt/"
    validate_certs: "no"
    tmp_dest: /tmp/
...
