---
- name: download component sources
  become: true
  become_user: root
  get_url:
    url: "{{ sources_prometheus }}"
    dest: "/opt/"
    validate_certs: "no"
    tmp_dest: /tmp/
  when: sources_result.stat.exists == False
...
