---
- name: Yum repo add for grafana
  copy:
    src: "grafana.repo"
    dest: "/etc/yum.repos.d/"
    
- name: Install Grafana using RPM
  yum:
    name: "{{ sources_grafana }}"
    state: present
  
- name: Enable grafana service 
  systemd:
    name: grafana-server
    enabled: yes

- name: Start grafana service
  systemd:
    name: grafana-server
    daemon_reload: yes
    state: restarted
...
